# This will appear before many messages from the plugin.
message-prefix: '&8[&cWbsQuake&8]'

# Use a minecraft colour code here to pick the message colour
message-colour: '7'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'


options:
  # Should the server economy be used, or should money be tracked internally?
  # When true, Vault must be installed.
  # When false, money earnt and spent in Quake will be tracked internally by this plugin as custom currency.
  use-economy: false

  # How should money be displayed when "use-economy" is set to false?
  # You can format this however you like, where "%money%" will be replaced with the number to format.
  # For example, setting this to "$%money%" will display something that costs 5 as "$5".
  economy-format: '◎%money%'

  # When true, players will respawn at the spawnpoint furthest from
  # any other player in the arena. When false, it's completely random.
  # With only 2 players, this uses a random spawnpoint except the closest one
  # (to prevent spawning at the same places every time on symmetrical maps)
  furthest-spawnpoint: true

  # When true, the scoreboard in game will show the players with the top 3 points.
  show-leaderboard-in-game: true

  # The distance away from the player's eye level a hit needs to be to count as a headshot
  headshots-threshold: 0.4

  # When true, headshots give 2 points instead of 1 (but still counts as 1 kill)
  headshots-give-bonus-points: false

  # How much money every kill should give
  money-per-kill: 10
  # Money per headshot is given as on top of the kill money.
  headshot-money-bonus: 5

  # How many players are stored in active memory (not including players in the lobby).
  # Higher numbers use more memory, but will speed up some operations.
  player-cache-size: 25

  # How many arenas should appear in votes.
  # Note that if there are fewer arenas with the correct min/max player counts,
  # there may be fewer than this many arenas shown.
  max-arenas-per-vote: 5

power-ups:
  rapid_fire: # You reference these in game to add to arenas
    type: rapid_fire # Types are: rapid_fire, multishot, bounceshot, and potion
    item: diamond_hoe # The item players see at power-ups in game.
    display: 'Rapid Fire' # The name here is what shows in game when activated by a player
    multiplier: 2
    duration: 300 # in ticks
    cooldown: 600 # How long until the next powerup regenerates

  speed:
    # Leaving out the display: fields will use the section name, auto-capitalized. This will show as "Speed"
    type: potion
    # Leaving out item uses a default. For potions, it's a speed potion.
    potion: speed
    amplifier: 3
    duration: 200 # in ticks
    target: player
    cooldown: 600

  invisibility:
    type: potion
    potion: invisibility
    item: phantom_membrane
    duration: 200
    cooldown: 500
    # You can leave out some variables and they'll use a default value.
    # Default target is player
    # Default amplifier is 1

  multishot:
    type: multishot
    duration: 100
    item: crossbow
    cooldown: 600

  scattershot:
    type: scattershot
    item: quartz
    amount: 3 # The amount of shots to fire in a random variation
    duration: 400
    cooldown: 600

  bounceshot:
    type: bounceshot
    duration: 300
    item: slime_ball
    bounces: 2 # How many times can the quake ray bounce off blocks before expiring
    cooldown: 600

  glow_others:
    type: potion
    potion: glowing
    item: spectral_arrow
    duration: 60
    cooldown: 600
    # You can choose different targets: player, all, random, all_not_player, random_not_player, closest
    target: not_player # Everyone except the player who activates it
  # target: all # Every player, including the one who activates it
  # target: random # A random player in the arena, including the player who activates it
  # target: random_not_player # A random player in the arena, excluding the player who activates it
  # target: player # The player who activates it
  # target: closest # The closest player to the player who activates it

  short_invis:
    type: potion
    potion: invisibility
    item: phantom_membrane
    duration: 80
    cooldown: 160

  glow_closest:
    type: potion
    potion: glowing
    item: spectral_arrow
    duration: 60
    cooldown: 600
    target: closest

  random:
    # Chooses a random power up from the list and applies that one.
    type: random
    display: 'Random' # This can be set, but is never used - the chosen powerup's display is shown instead!
    item: chest
    cooldown: 600
    power-ups:
      - invisibility
      - glow_others
      - speed